
export const cansonColors = [
    { name: 'Blanc', hex: '#FFFFFF' },
    { name: 'Blanc nuage', hex: '#ebe1e0' },
    { name: 'Citronnelle', hex: '#e4cea9' },
    { name: 'Ivoire', hex: '#ecc49a' },
    { name: 'Bouton d’or', hex: '#f9be4e' },
    { name: 'Saumon', hex: '#ec8831' },
    { name: 'Jaune soleil', hex: '#fd9010' },
    { name: 'Orange', hex: '#f5611d' },
    { name: 'Coquelicot', hex: '#de3429' },
    { name: 'Rouge vif', hex: '#cc2424' },
    { name: 'Marron foncé', hex: '#694722' },
    { name: 'Havane clair', hex: '#ad5d16' },
    { name: 'Cachou', hex: '#a66f2d' },
    { name: 'Chanvre', hex: '#cd9c60' },
    { name: 'Lichen', hex: '#dfb988' },
    { name: 'Coquille', hex: '#d6b89c' },
    { name: 'Lys', hex: '#d2c0ab' },
    { name: 'Gris trianon', hex: '#bfa58a' },
    { name: 'Gris clair', hex: '#bda89b' },
    { name: 'Gris flanelle', hex: '#b9a491' },
    { name: 'Gris fumée', hex: '#a69077' },
    { name: 'Gris chiné', hex: '#9f876f' },
    { name: 'Marron glacé', hex: '#96715f' },
    { name: 'Cannelle', hex: '#a0613e' },
    { name: 'Violet', hex: '#9f4773' },
    { name: 'Rose vénitien', hex: '#c56162' },
    { name: 'Rose foncé', hex: '#d38a7b' },
    { name: 'Aurore', hex: '#f2cdbb' },
    { name: 'Lilas', hex: '#d3c1cc' },
    { name: 'Azur', hex: '#d0dcec' },
    { name: 'Bleu Alaska', hex: '#d1d5e0' },
    { name: 'Bleu clair', hex: '#8698a3' },
    { name: 'Bleu acier', hex: '#9ca8b5' },
    { name: 'Bleu turquoise', hex: '#379fc6' },
    { name: 'Outremer', hex: '#373f88' },
    { name: 'Bleu pétrole', hex: '#204c65' },
    { name: 'Bleu indigo', hex: '#353954' },
    { name: 'Vert océan', hex: '#585b2f' },
    { name: 'Vert olive', hex: '#6a6347' },
    { name: 'Sauge', hex: '#5e7561' },
    { name: 'Vert billard', hex: '#1c8d56' },
    { name: 'Vert pomme', hex: '#9dae4c' },
    { name: 'Vert amande', hex: '#b4b17b' },
    { name: 'Gris ciel', hex: '#b1b2aa' },
    { name: 'Gris perle', hex: '#c9bfb6' },
    { name: 'Gris lunaire', hex: '#b1a4a1' },
    { name: 'Graphite', hex: '#6d6361' },
    { name: 'Gris ardoise', hex: '#625856' },
    { name: 'Gris anthracite', hex: '#4f4a47' },
    { name: 'Noir', hex: '#1d1e22' }
  ];