
sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                before_switchers_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 35
                    context:
                        event: sylius.shop.layout.before_currency_switcher
                currency_switcher:
                    template: "@SyliusShop/Layout/Topbar/_currencySwitcher.html.twig"
                    priority: 30
                locale_switcher:
                    template: "@SyliusShop/Layout/Topbar/_localeSwitcher.html.twig"
                    priority: 20
                before_security_widget_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 15
                    context:
                        event: sylius.shop.layout.before_security_widget
                security_widget:
                    template: "@SyliusShop/Layout/Topbar/_securityWidget.html.twig"
                    priority: 10
                after_security_widget_legacy:
                    template: "@SyliusUi/Block/_legacySonataEvent.html.twig"
                    priority: 5
                    context:
                        event: sylius.shop.layout.after_security_widget

        sylius.shop.homepage:
            blocks:
                # front_products:
                #     template: "@SyliusShop/Homepage/_frontProducts.html.twig"
                #     priority: 55
                # mis_en_avant_products:
                #     template: "@SyliusShop/Homepage/_mis-en-avant_Products.html.twig"
                #     priority: 60
                # banner:
                #     template: "@SyliusShop/Homepage/_banner.html.twig"
                #     priority: 60
                # tableaux_products:
                #     template: "@SyliusShop/Homepage/_tableauxProducts.html.twig"
                #     priority: 45
                # latest_products:
                #     template: "@SyliusShop/Homepage/_latestProducts.html.twig"
                #     priority: 50
                # latest_products_carousel:
                #     template: "@SyliusShop/Homepage/_latestProductsCarousel.html.twig"
                #     priority: 40
                newsletter:
                    template: "@SyliusShop/Homepage/_newsletter.html.twig"
                    priority: 30
                # products_grid:
                #     template: "@SyliusShop/Homepage/_productsGrid.html.twig"
                #     priority: 20
                about_us:
                    template: "@SyliusShop/Homepage/_aboutUs.html.twig"
                    priority: 10